### ISSUE TITLE
Fine tuning on GUI

### ISSUE THREAD

**Issue by lbusett** [ranghetti/fidolasen#30]
Some final suggestions to fine-tune the current GUI: Most are only cosmetic (e.g., change/reword labels). 
Only a couple of places where we can maybe move content (see if you agree).

Implement what you agree upon, discard what you don't think makes sense, and let's talk about the rest.

# Main Panel

## Required Output Type 
  --> Proposed Label change: "Required output type" --> "Type of processing"
  --> Proposed Label change:  "Processed spatial files (surface reflectance, spectral indices, ...)"           |-> Download SAFE files and process them (resize, mosaic, compute indices....)
              |-> Only Download SAFE files (perform atmospheric correction if needed)

## Select products and sensors

  --> Maybe in the future add a "Spectral Indexes" checkbox, which activates/deactivatesthe "Index Selection panel" ? 

## SAFE options

--> Proposed Label change: "SAFE options" --> "Download Options"

--> Proposed Label changes:
   "Download mode --> Offline (process only already available SAFE images)"
   "Overwrite **existing** SAFE images?"
                          |-> "Yes (re-download all images and re-apply sen2cor if needed)"
                          |-> "No (skip download/atmospheric correction for existing images)"

## Atmospheric correction options

--> Proposed Label changes:
  --> "Only use L2A (dates for which L1C is avaliable but L2A not will not be processed (The part in parenthesis can be a Note))"
  --> "Use level2A if available, otherwise use L1C and correct it with sen2cor locally "
  --> "Always use L1C and correct it with sen2cor locally"
  
  Question: L'opzione 2 (che diventerebbe la 3) non dovrebbe fare comparire la selezione del folder per L1c ? O alla fine lo hai tolto ? 
 Note;  La label "Method to obtain level-2A corrected images" si può anche togliere, ma é uguale

# Spatial-temporal selection 
    --> Spatio-Temporal selection ? 

## Spatial extent

   "Use as extent" --> Maybe change label to: "Select extent"
    --> Maybe change "Draw on the map" to "Draw on map" (+ it could go on the top of the checklist, and "Bounding box coordinates"  could go on the bottom and become "Enter Bounding box coordinates" or "Enter coordinates")
   "Number of output extents" -->  Maybe change to "Cropping Options"  or "Mosaicing Options"  ? 
                 |-> "Unique (Mosaic all polygons to a single output)"
                 |-> "Multiple (Create separate outputs for each polygon)"

## Processing Settings
  --> Maybe change to "Processing Options" ? 

  --> Maybe add a panel at the top, only containing "Main Output Folder" and the folder selector / group products radio button + "Overwrite existing outputs" checkbox

### Output Extent

  --> Proposed Label change: "Clip outputs on the selected extent?"
  --> Proposed Label change: "No (Outputs will include the full extent of the tiles intersecting the selected extent)"
  --> Proposed Label change: "Mask outside the polygons?" --> "Mask data outside the selected polygon(s)? 
  --> Proposed Label change: "Keep the single tiles?" --> "Save single tiles?"
  --> Proposed Label change: "Keep the tile mosaics?" --> "Save mosaiced tiles?"
  --> Proposed Label change: "Directory for single tiles in custom format:" --> "Output folder for single tiles:"
  --> Proposed Label change: "Directory for tiles spatially merged:" --> "Output folder for mosaiced tiles:"

### Atmospheric mask

  --> Suggestion for future versions: If Mask cloud-covered pixels is selected, but user didn't select SCL, 
      then masking is done, but the SCL is deleted after use (similar to what we do in MODIStsp if a user selects a QI which needs an original layer, but did not select that original layer)

### Output Geometry

  --> Proposed Label change: "Use an existing raster as a reference for output grid?" --> "Use an existing raster to define the output grid?"
  --> Proposed Label change: "Yes (load raster)" --> "Yes", and if possible change the label of the button to   "Select raster file"
  --> Proposed Label change: "Use the file as a reference for:" --> "Use the file to define:"

  --> Possible change: "Overwrite existing outputs": Maybe move this together with the main output folder selector at the top ? It is not related to the format, but to the folder were we place the outputs

## Index selection
  --> Maybe change to "Select Spectral Indexes" ? 

## Save/Export parameters
 
  --> Proposed Label change: "Export Parameters" --> "Save Options"
  --> Proposed Label change: "Import Parameters" --> "Load Options"

  --> Question: What does it happen if I Save and Close GUI without specifying an output file ? 
  --> Question: What does it happen if clck Save ancd close but parameters are "incomplete (e.g., missing output folders, etc. ?

**Comment by ggranga** [comment]
## Main Panel

### Required Output Type 

>   --> Proposed Label change: "Required output type" --> "Type of processing"

I agree; done.

>  --> Proposed Label change:  "Processed spatial files (surface reflectance, spectral indices, ...)"           |-> Download SAFE files and process them (resize, mosaic, compute indices....)
              |-> Only Download SAFE files (perform atmospheric correction if needed)

I disagree: this would presume that the download would already be performed, while these options works either in online and offline mode. I slightly changed the labels in:
- _Processed spatial files (surface reflectance, spectral indices, ...) in custom format_ (to highlight that the output will be in a different file format)
- _Raw files in [raw SAFE format](https://earth.esa.int/web/sentinel/user-guides/sentinel-2-msi/data-formats) (downloaded and/or corrected with sen2cor)_ (to highlight that SAFE is the format, with the link to help people not knowing about it; this will be useful also below in the GUI).

### Select products and sensors

>  --> Maybe in the future add a "Spectral Indexes" checkbox, which activates/deactivatesthe "Index Selection panel" ? 

I agree (done).

### SAFE options

> --> Proposed Label change: "SAFE options" --> "Download Options"

No, for the same reason as above (this box is valid also for offline mode, to define the input SAFE directories, and to define overwrite option which is used also in offline mode if sen2cor is required).
Moreover, this box does not complete the options related to download (i.e., Spatio-temporal selection parameters).
Probably the addition of the link in the first box will help to understand what SAFE is.

> --> Proposed Label changes:
   "Download mode --> Offline (process only already available SAFE images)"
   "Overwrite **existing** SAFE images?"
                          |-> "Yes (re-download all images and re-apply sen2cor if needed)"
                          |-> "No (skip download/atmospheric correction for existing images)"

Done (you already asked this by voice, but I forgot it).

### Atmospheric correction options

--> Proposed Label changes:
  --> "Only use L2A (dates for which L1C is avaliable but L2A not will not be processed (The part in parenthesis can be a Note))"
  --> "Use level2A if available, otherwise use L1C and correct it with sen2cor locally "
  --> "Always use L1C and correct it with sen2cor locally"

I made some changes in the labels, basing on your suggestions (but with some changes, due to the fact that you refer to precorrected images as L2A, but also outputs of sen2cor are L2A). Labels are shorten, with notes as integrations.
  
>  Question: L'opzione 2 (che diventerebbe la 3) non dovrebbe fare comparire la selezione del folder per L1c ? O alla fine lo hai tolto ? 

Vero, mancava un controllo; sistemato.

> Note;  La label "Method to obtain level-2A corrected images" si può anche togliere, ma é uguale

Al momento sì perchè c'è solo un'opzione per sen2cor, ma in futuro potrebbe esserci la possibilità di aggiungerne altre (precorretti theia, scelta del DEM, altri algoritmi di correzione atmosferica, ...), quindi lo lascerei.

## Spatial-temporal selection 
>    --> Spatio-Temporal selection ? 

Ok (or "querying parameters"?)

### Spatial extent

>   "Use as extent" --> Maybe change label to: "Select extent"

Ok ("Method to select extent")

>    --> Maybe change "Draw on the map" to "Draw on map" (+ it could go on the top of the checklist, and "Bounding box coordinates"  could go on the bottom and become "Enter Bounding box coordinates" or "Enter coordinates")

Ok 

>   "Number of output extents" -->  Maybe change to "Cropping Options"  or "Mosaicing Options"  ? 
                 |-> "Unique (Mosaic all polygons to a single output)"
                 |-> "Multiple (Create separate outputs for each polygon)"

Technically it is not correct ("to mosaic" means to create mosaicked (tiled) rasters, not to merge). 
Changed using notes.

## Processing Settings
>  --> Maybe change to "Processing Options" ? 

Ok

>  --> Maybe add a panel at the top, only containing "Main Output Folder" and the folder selector / group products radio button + "Overwrite existing outputs" checkbox

Done (also the file format was put here).

### Output Extent

>  --> Proposed Label change: "Clip outputs on the selected extent?"

Ok

>  --> Proposed Label change: "No (Outputs will include the full extent of the tiles intersecting the selected extent)"

Too long (using a note).

>  --> Proposed Label change: "Mask outside the polygons?" --> "Mask data outside the selected polygon(s)? 

Ok

>  --> Proposed Label change: "Keep the single tiles?" --> "Save single tiles?"
  --> Proposed Label change: "Keep the tile mosaics?" --> "Save mosaiced tiles?"

Ok ("merged tiles" instead of "mosaiced")

>  --> Proposed Label change: "Directory for single tiles in custom format:" --> "Output folder for single tiles:"
  --> Proposed Label change: "Directory for tiles spatially merged:" --> "Output folder for mosaiced tiles:"

Ok (maintaining "directory").

### Atmospheric mask

>  --> Suggestion for future versions: If Mask cloud-covered pixels is selected, but user didn't select SCL, 
      then masking is done, but the SCL is deleted after use (similar to what we do in MODIStsp if a user selects a QI which needs an original layer, but did not select that original layer)

It already works in this way.

### Output Geometry

>  --> Proposed Label change: "Use an existing raster as a reference for output grid?" --> "Use an existing raster to define the output grid?"
  --> Proposed Label change: "Yes (load raster)" --> "Yes", and if possible change the label of the button to   "Select raster file"
  --> Proposed Label change: "Use the file as a reference for:" --> "Use the file to define:"

Ok

>  --> Possible change: "Overwrite existing outputs": Maybe move this together with the main output folder selector at the top ? It is not related to the format, but to the folder were we place the outputs

Moved in the box with output directory.

## Index selection
>  --> Maybe change to "Select Spectral Indexes" ? 

I prefer not to use verbs,since all the tabs names are names. Maybe "Spectral indices selection" or simply "Spectral indices"?

## Save/Export parameters
 
>  --> Proposed Label change: "Export Parameters" --> "Save Options"
  --> Proposed Label change: "Import Parameters" --> "Load Options"

Ok

>  --> Question: What does it happen if I Save and Close GUI without specifying an output file ? 
  --> Question: What does it happen if clck Save ancd close but parameters are "incomplete (e.g., missing output folders, etc. ? 

I have not yet implemented the checks for coherence between parameters and for missing values (a message will appear, leaving the user to set required parameters or edit conflicting ones).

**Comment by lbusett** [comment]
👍🖖 sulle labels, é piu che altro questione di "gusti". Per cui lascio a te decisione! L'importante é che (secondo me), cambiando quelle 3 4 cose organizzative ora il tutto risulta più chiaro. 👍
