### ISSUE TITLE
Replace `import()` with `import_from_path()` when loading a python module

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/fidolasen#35]
Do not write on the system python global env, but only use absolute paths

**Comment by rcabas** [comment]
hi Luigi, I have use the function "read_scihub_login()" to know which is the username and password that I am using in my downloads...
The problem is I do not know where is the "apihub.txt" in linux, and when I try to use the function "write_scihub_login()", i cannot fint "import_from_path()" function.
Can you help me? or even, tell me where is the user and password in Linux... 
I am not using GUI becouse I have only install R and docker sen2r apps... I do not have graphical interface in this machine. All I do trough console.
Thanks!!

**Comment by ranghetti** [comment]
Hi @rcabas ,
can you report the problem opening a new issue? In that issue, report the output of commands
```r
read_scihub_login()
write_scihub_login("your_username", "your_password")
```
